spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # This would create a schema every time the app is started and would destroy it on shutdown
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
